[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "touchpy"
version = "0.1.0"
description = "Toolkit providing various interconnectivity tools between TouchDesigner and Python."
authors = []
license = { file = "LICENSE" }
readme = "README.md"
requires-python = "3.11"
dependencies = [
    "pytorch-cuda==11.8",
    "torchvision",
    "torchaudio",
    "numpy==1.26"
]
[project.urls]
repository = "https://intentdev.dev/touchpy"

[tool.setuptools]
packages = ["modules"] 
package_data = { 
    "modules": ["*.pyd"], 
    }