name: Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.27
        with:
          cuda: "12.6.0"
          method: network
          sub-packages: '["nvcc", "cudart"]'
          use-github-cache: false
          use-local-cache: false

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.0.5
        with:
          vulkan_version: 1.3.290.0
          install_runtime: false
          cache: true

      - name: Build and install touchpy
        run: pip install . -v

      - name: Install docs dependencies
        run: pip install -r docs/requirements.txt

      - name: Build documentation
        run: sphinx-build -M html docs/source docs/build

      - name: Deploy to docs branch
        uses: peaceiris/actions-gh-pages@v4
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: docs
          force_orphan: false
